export const GET_PAGE_REQUEST = "GET_PAGE_REQUEST";
export const GET_PAGE_SUCCESS = "GET_PAGE_SUCCESS";
export const GET_PAGE_FAILURE = "GET_PAGE_FAILURE";
export const GET_PAGE_RESET = "GET_PAGE_RESET";

export const GET_PAGES_REQUEST = "GET_PAGES_REQUEST";
export const GET_PAGES_SUCCESS = "GET_PAGES_SUCCESS";
export const GET_PAGES_FAILURE = "GET_PAGES_FAILURE";

export const CREATE_PAGE_REQUEST = "CREATE_PAGE_REQUEST";
export const CREATE_PAGE_SUCCESS = "CREATE_PAGE_SUCCESS";
export const CREATE_PAGE_FAILURE = "CREATE_PAGE_FAILURE";
export const CREATE_PAGE_RESET = "CREATE_PAGE_RESET";

export const UPDATE_PAGE_REQUEST = "UPDATE_PAGE_REQUEST";
export const UPDATE_PAGE_SUCCESS = "UPDATE_PAGE_SUCCESS";
export const UPDATE_PAGE_FAILURE = "UPDATE_PAGE_FAILURE";

export const UPDATE_DOMAIN_REQUEST = "UPDATE_DOMAIN_REQUEST";
export const UPDATE_DOMAIN_SUCCESS = "UPDATE_DOMAIN_SUCCESS";
export const UPDATE_DOMAIN_FAILURE = "UPDATE_DOMAIN_FAILURE";
export const UPDATE_DOMAIN_RESET = "UPDATE_DOMAIN_RESET";

export const UPDATE_MAIN_IMAGE_REQUEST = "UPDATE_MAIN_IMAGE_REQUEST";
export const UPDATE_MAIN_IMAGE_SUCCESS = "UPDATE_MAIN_IMAGE_SUCCESS";
export const UPDATE_MAIN_IMAGE_FAILURE = "UPDATE_MAIN_IMAGE_FAILURE";

export const UPDATE_PROFILE_IMAGE_REQUEST = "UPDATE_PROFILE_IMAGE_REQUEST";
export const UPDATE_PROFILE_IMAGE_SUCCESS = "UPDATE_PROFILE_IMAGE_SUCCESS";
export const UPDATE_PROFILE_IMAGE_FAILURE = "UPDATE_PROFILE_IMAGE_FAILURE";

export const ADD_SOCIAL_LINK_REQUEST = "ADD_SOCIAL_LINK_REQUEST";
export const ADD_SOCIAL_LINK_SUCCESS = "ADD_SOCIAL_LINK_SUCCESS";
export const ADD_SOCIAL_LINK_FAILURE = "ADD_SOCIAL_LINK_FAILURE";
